// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Suhaan-Bhandary/fundraiser-management/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// AdminStorer is an autogenerated mock type for the AdminStorer type
type AdminStorer struct {
	mock.Mock
}

// GetAdminIDPassword provides a mock function with given fields: username
func (_m *AdminStorer) GetAdminIDPassword(username string) (uint, string, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminIDPassword")
	}

	var r0 uint
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (uint, string, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) uint); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(username)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterAdmin provides a mock function with given fields: req
func (_m *AdminStorer) RegisterAdmin(req dto.RegisterAdminRequest) error {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for RegisterAdmin")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.RegisterAdminRequest) error); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminStorer creates a new instance of AdminStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminStorer {
	mock := &AdminStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
