// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdminStorer is an autogenerated mock type for the AdminStorer type
type AdminStorer struct {
	mock.Mock
}

// NewAdminStorer creates a new instance of AdminStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminStorer {
	mock := &AdminStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
