// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Suhaan-Bhandary/fundraiser-management/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// DonationStorer is an autogenerated mock type for the DonationStorer type
type DonationStorer struct {
	mock.Mock
}

// CreateDonation provides a mock function with given fields: donationDetail
func (_m *DonationStorer) CreateDonation(donationDetail dto.CreateDonationRequest) (uint, error) {
	ret := _m.Called(donationDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateDonation")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateDonationRequest) (uint, error)); ok {
		return rf(donationDetail)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateDonationRequest) uint); ok {
		r0 = rf(donationDetail)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateDonationRequest) error); ok {
		r1 = rf(donationDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDonations provides a mock function with given fields:
func (_m *DonationStorer) ListDonations() ([]dto.FundraiserDonationView, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListDonations")
	}

	var r0 []dto.FundraiserDonationView
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.FundraiserDonationView, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.FundraiserDonationView); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FundraiserDonationView)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFundraiserDonations provides a mock function with given fields: fundraiserId
func (_m *DonationStorer) ListFundraiserDonations(fundraiserId uint) ([]dto.FundraiserDonationView, error) {
	ret := _m.Called(fundraiserId)

	if len(ret) == 0 {
		panic("no return value specified for ListFundraiserDonations")
	}

	var r0 []dto.FundraiserDonationView
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.FundraiserDonationView, error)); ok {
		return rf(fundraiserId)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.FundraiserDonationView); ok {
		r0 = rf(fundraiserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FundraiserDonationView)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(fundraiserId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserDonations provides a mock function with given fields: userId
func (_m *DonationStorer) ListUserDonations(userId uint) ([]dto.DonationView, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for ListUserDonations")
	}

	var r0 []dto.DonationView
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]dto.DonationView, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uint) []dto.DonationView); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DonationView)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDonationStorer creates a new instance of DonationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDonationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DonationStorer {
	mock := &DonationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
