// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DonationStorer is an autogenerated mock type for the DonationStorer type
type DonationStorer struct {
	mock.Mock
}

// NewDonationStorer creates a new instance of DonationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDonationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DonationStorer {
	mock := &DonationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
