// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Suhaan-Bhandary/fundraiser-management/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// DonationStorer is an autogenerated mock type for the DonationStorer type
type DonationStorer struct {
	mock.Mock
}

// CreateDonation provides a mock function with given fields: donationDetail
func (_m *DonationStorer) CreateDonation(donationDetail dto.CreateDonationRequest) (uint, error) {
	ret := _m.Called(donationDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateDonation")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.CreateDonationRequest) (uint, error)); ok {
		return rf(donationDetail)
	}
	if rf, ok := ret.Get(0).(func(dto.CreateDonationRequest) uint); ok {
		r0 = rf(donationDetail)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(dto.CreateDonationRequest) error); ok {
		r1 = rf(donationDetail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListDonationsCount provides a mock function with given fields: req
func (_m *DonationStorer) GetListDonationsCount(req dto.ListDonationsRequest) (uint, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetListDonationsCount")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListDonationsRequest) (uint, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListDonationsRequest) uint); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(dto.ListDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListFundraiserDonationsCount provides a mock function with given fields: req
func (_m *DonationStorer) GetListFundraiserDonationsCount(req dto.ListFundraiserDonationsRequest) (uint, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetListFundraiserDonationsCount")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListFundraiserDonationsRequest) (uint, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListFundraiserDonationsRequest) uint); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(dto.ListFundraiserDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetListUserDonationsCount provides a mock function with given fields: req
func (_m *DonationStorer) GetListUserDonationsCount(req dto.ListUserDonationsRequest) (uint, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetListUserDonationsCount")
	}

	var r0 uint
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListUserDonationsRequest) (uint, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListUserDonationsRequest) uint); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(uint)
	}

	if rf, ok := ret.Get(1).(func(dto.ListUserDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListDonations provides a mock function with given fields: req
func (_m *DonationStorer) ListDonations(req dto.ListDonationsRequest) ([]dto.FundraiserDonationView, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ListDonations")
	}

	var r0 []dto.FundraiserDonationView
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListDonationsRequest) ([]dto.FundraiserDonationView, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListDonationsRequest) []dto.FundraiserDonationView); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FundraiserDonationView)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.ListDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListFundraiserDonations provides a mock function with given fields: req
func (_m *DonationStorer) ListFundraiserDonations(req dto.ListFundraiserDonationsRequest) ([]dto.FundraiserDonationView, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ListFundraiserDonations")
	}

	var r0 []dto.FundraiserDonationView
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListFundraiserDonationsRequest) ([]dto.FundraiserDonationView, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListFundraiserDonationsRequest) []dto.FundraiserDonationView); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.FundraiserDonationView)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.ListFundraiserDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUserDonations provides a mock function with given fields: req
func (_m *DonationStorer) ListUserDonations(req dto.ListUserDonationsRequest) ([]dto.DonationView, error) {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ListUserDonations")
	}

	var r0 []dto.DonationView
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.ListUserDonationsRequest) ([]dto.DonationView, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(dto.ListUserDonationsRequest) []dto.DonationView); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.DonationView)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.ListUserDonationsRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDonationStorer creates a new instance of DonationStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDonationStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DonationStorer {
	mock := &DonationStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
