// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Suhaan-Bhandary/fundraiser-management/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// FundraiserStorer is an autogenerated mock type for the FundraiserStorer type
type FundraiserStorer struct {
	mock.Mock
}

// CreateFundraiser provides a mock function with given fields: fundDetail
func (_m *FundraiserStorer) CreateFundraiser(fundDetail dto.CreateFundraiserRequest) error {
	ret := _m.Called(fundDetail)

	if len(ret) == 0 {
		panic("no return value specified for CreateFundraiser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.CreateFundraiserRequest) error); ok {
		r0 = rf(fundDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewFundraiserStorer creates a new instance of FundraiserStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFundraiserStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *FundraiserStorer {
	mock := &FundraiserStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
