// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	dto "github.com/Suhaan-Bhandary/fundraiser-management/internal/pkg/dto"
	mock "github.com/stretchr/testify/mock"
)

// OrganizerStorer is an autogenerated mock type for the OrganizerStorer type
type OrganizerStorer struct {
	mock.Mock
}

// GetOrganizerIDPassword provides a mock function with given fields: email
func (_m *OrganizerStorer) GetOrganizerIDPassword(email string) (int, string, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganizerIDPassword")
	}

	var r0 int
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (int, string, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RegisterOrganizer provides a mock function with given fields: orgDetail
func (_m *OrganizerStorer) RegisterOrganizer(orgDetail dto.RegisterOrganizerRequest) error {
	ret := _m.Called(orgDetail)

	if len(ret) == 0 {
		panic("no return value specified for RegisterOrganizer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(dto.RegisterOrganizerRequest) error); ok {
		r0 = rf(orgDetail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyOrganizer provides a mock function with given fields: organizerId
func (_m *OrganizerStorer) VerifyOrganizer(organizerId int) error {
	ret := _m.Called(organizerId)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOrganizer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(organizerId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrganizerStorer creates a new instance of OrganizerStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrganizerStorer(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrganizerStorer {
	mock := &OrganizerStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
